services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nutri_habits
      POSTGRES_PASSWORD: nutri_habits
      POSTGRES_DB: nutri_habits
    ports:
      - '5432:5432'
    volumes:
      - nutri-habits-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nutri_habits']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nutri-habits-db:
